Linux背景详解--初版完成
tinyclub/lad-book pull request #8
Opened 2017-12-03 13:07 UTC by lina-not-linus

Linux背景详解--初版完成

2017-12-03 13:08 UTC, lina-not-linus commented
重新fork；增加参考文献部分；整理历史记录为一次commit

2017-12-03 14:22 UTC, lzufalcon requested changes
主要还是格式问题，中英文、数字混排，中英文符号混用等问题。

2017-12-03 14:22 UTC, lzufalcon commented on zh-cn/background/history.md
> +Linux 是一种自由和开放源代码的类 UNIX 操作系统。目前运用领域最广泛、使用人数最多的操作系统。该操作系统的内核由林纳斯·托瓦兹在1991年10月5日首次发布。
1. 也是 目前，必要的过渡
2. 其实这里也可以直接用 Linus
3. 数字和英文一样，在中英文混排时，需要添加必要的空格。

2017-12-03 14:22 UTC, lzufalcon commented on zh-cn/background/history.md
> + Linux 最初是作为支持英特尔x86架构的个人电脑的一个自由操作系统。目前 Linux 已经被移植到更多的计算机硬件平台，远远超出其他任何操作系统。 Linux 可以运行在服务器和其他大型平台之上，如大型主机和超级计算机。 Linux 也广泛应用在嵌入式系统上，如手机、平板电脑、路由器、电视和电子游戏机等。
1. Linux 前面没有中文，这里的空格可以去掉。类似地，如果前面是前后是符号，也不需要加额外空格。可以结合实际情况看哈。
2. x86 前后增加空格

2017-12-03 14:22 UTC, lzufalcon commented on zh-cn/background/history.md
> +## Linux 背景详解
建议直接使用一级标题？只要一个 # 号，后面类似都可以去掉一个 # 号。

2017-12-03 14:22 UTC, lzufalcon commented on zh-cn/background/history.md
> + UNIX 操作系统，是美国 AT&T 公司贝尔实验室于1969年完成的操作系统。最早由肯·汤普逊（Ken Thompson），丹尼斯·里奇（Dennis Ritchie），道格拉斯·麦克罗伊（Douglas McIlroy），和乔伊·欧桑纳于1969年在 AT&T 贝尔实验室开发。于1971年首次发布，最初是完全用汇编语言编写。1973年，Unix 被丹尼斯·里奇用 C 语言（内核和 I/O
1. 1969 数字前后英文，后续类似格式不再注明，请自行修改。
2. 和前面的 ， 可以去掉
3. 能前面可以加个 也，表示衔接

2017-12-03 14:22 UTC, lzufalcon commented on zh-cn/background/history.md
> +由于 Unix 系统设计简洁并且在发布时提供源代码,许多其他组织和团体对其进行了扩展，最著名当属加州伯克利分校．他们推出了 Berkeley Software Distributions(BSD）。
标点符号没有完全统一，这里的，和。都需要改为中文的全角，请记得修改。全文通用。

2017-12-03 14:22 UTC, lzufalcon commented on zh-cn/background/history.md
> +由于 Unix 的高度可移植性与强大的效能，加上当时并没有版权的纠纷， 所以让很多商业公司开始了 Unix 操作系统的发展，例如 AT&T 自家的 System V、IBM 的 AIX 以及 HP 与 DEC 等公司， 都有推出自家的主机搭配自己的类 Unix 操作系统。但是，每家公司推出的硬件架构不同，加上当时没有所谓的协议的概念，导致开发出来的 Unix 操作系统以及内含的相关软件并没有办法
1. 都有推出，前面多了一个空格。
2. x86 建议大写为 X86，可以全文替换。

2017-12-03 14:22 UTC, lzufalcon commented on zh-cn/background/history.md
> +由于1979年的版权声明的影响，促使 Andrew Tanenbaum (谭宁邦)教授自己动手开始编写用于教育用途的 Minix 这个类 Unix 的核心程序．在撰写的过程中，为了避免版权纠纷，谭宁邦完全不看 Unix 核心原代码！ 并且强调他编写的 Minix 系统与 Unix 系统兼容！到1986年 Minix 开发工作终于完成。Minix 并不是完全免费的，无法在网络上提供下载，必须要通过
1. 括号没有用中文格式（），以及中文句点 。又用到了 .

2017-12-03 14:22 UTC, lzufalcon commented on zh-cn/background/history.md
> +由于商业的考虑，以及在当时现实环境下的思考， AT&T 在1979年发行的第七版 Unix 中，特别提到了 『不可对学生提供源代码』的严格限制！ 同时，也造成 Unix 业界之间的紧张气氛，并且也引爆了很多的商业纠纷
1. 这句最后缺少句号 。
2. 关于 Unix 的发展史，建议顺带提一提，目前还留存的 Unix 系统，比如 FreeBSD 等等，Solaris 随着 Sun 等倒台退出历史？可以检索相关资料补全更多类似信息。

2017-12-03 14:22 UTC, lzufalcon commented on zh-cn/background/history.md
> +GNU 项目开发出许多高质量的免费软件，其中包括有名的 emacs 编辑系统、bash shell 程序、gcc 系列编译程序、gdb 调试程序等等。不过，对于 GNU 的最初构想 『建立一个自由的 Unix 操作系统』来说，有这些优秀的程序是仍无法满足， 因为，当时并没有『自由的 Unix 核心』存在．所以这些软件仍只能在那些有专利的 Unix 平台上工作，一直到 Linux 的出现．
1. 有这些优秀的程序是仍无法满足 后面看是否要加一个 的。
2. 同样有中文符号的问题

2017-12-03 14:22 UTC, lzufalcon commented on zh-cn/background/history.md
> +1988年，Linus Torvalds (托瓦兹)进入了赫尔辛基大学，并选读了计算机科学系。在读期间，接触到了 Unix 系统．当时整个赫尔辛基只有一部最新的 Unix 系统，同时仅提供16个终端(terminal)。 早期的计算机仅有主机具有运算功能，terminal 仅负责提供 Input/Output 而已。在这种情况下， 实在很难满足托瓦兹的需求，不久之后，他就知道有一个类似 Unix
1. 关于 Linus Torvards 人名的称呼，建议全文保持一致，比如说 Linux Torvards （林纳斯·托瓦兹）
2. terminal 首字母建议大写，包括前面的 bash, gcc, gdb，例如 Terminal, Bash, Gcc, Gdb
3. 386 后面建议加空格
4. Minix 前面用中文连接符如何？ ——
5. 同样有中文符号用了英文符号的情况，比如句号

2017-12-03 14:22 UTC, lzufalcon commented on zh-cn/background/history.md
> +由于谭宁邦教授只愿意将 Minix 系统用于教学，不愿意强化系统功能，导致大部分工程师不满足与已有的功能，也使托瓦兹萌生自己编写操作系统的想法．而 GNU 计划产出的 bash 工作环境和 gcc 编译程序等自由软件，让托瓦兹能够顺利的编写内核程序．最终，在 1991 年，他写出了能够在386计算机上运行的内核，并将其上传网上，提供下载．为了让更多 Unix 系统上的软在运行在 Linux 上，
1. 教授名称建议统一格式，比如 Andrew Tanenbaum（谭宁邦）
2. 不满足与 --> 不满足于
3. bash, gcc --> Bash, Gcc
4. 上传网上 --> 上传到网络上 ?
5. 为了让更多 Unix 系统上的软在 --> 为了让更多 Unix 系统上的软件
6. 最后一个 Linux后面不需要空格，但是记得换成中文，号。Linux，
7. 最后一个中文符号。

2017-12-03 14:22 UTC, lzufalcon commented on zh-cn/background/history.md
> +Linux操作系统从诞生到1.0版正式出现，共发布了下表中所示的一些主要版本(引用自《Linux内核完全剖析》赵炯编著的P5)。
1. 中英文、数字混排格式
2. 括号使用中文格式（）
3. P5 建议直接写上 第五页。

2017-12-03 14:22 UTC, lzufalcon commented on zh-cn/background/history.md
> +| ------ | ------------- | ---- |
表格中的说明部分，也请遵守中英文混排规则。

2017-12-03 14:22 UTC, lzufalcon commented on zh-cn/background/history.md
> +Linux的内核版本编号如下所示：
这一句可以去掉？

2017-12-03 14:22 UTC, lzufalcon commented on zh-cn/background/history.md
> +目前最新的内核版本是2017年11月24日公布的4.14.2版， Linux 内核版本号命名的规则：r.x.y
1. 数字和中文混排。
2.， Linux 中间的空格可以去掉
3. 的规则 后加个 为 字

2017-12-03 14:22 UTC, lzufalcon commented on zh-cn/background/history.md
> + GNU 计划的支持者与开发者，特别是其创立者理查德·斯托曼主张 Linux 应称为“ GNU/Linux ”较为恰当，因为此类操作系统使用了众多 GNU 程序，包含 Bash （ Shell 程序）、库、编译器等等作为 Linux 内核上的系统包． Linux 社区中的一些成员，如埃里克·雷蒙、林纳斯·托瓦兹等人，偏好 Linux 的名称，认为 Linux 朗朗上口，短而好记，拒绝使用“ GN
1. Stallman 等人名建议统一下格式 英文（中文），或者除了第一次出现使用这类格式外，其他地方统一为比较常见的简写，比如 Linus, Stallman 等
2. 中文符号

2017-12-03 14:22 UTC, lzufalcon commented on zh-cn/background/history.md
> +**参考文献**
建议使用段落方式，比如：##

2017-12-03 14:22 UTC, lzufalcon commented on zh-cn/background/history.md
> +1 赵炯. Linux 内核完全剖析[M]. 北京:机械工业出版社, 2016.
格式上，我们稍微统一一下，比如：

1. 书名，作者名，出版社，出版时间。
2. 中文字符格式，记得切换为全角
3. 序号后面记得加 . 号

2017-12-05 11:38 UTC, bjwrkj commented
commit 签名请使用英文，可配置自己的签名模板。

2017-12-09 14:02 UTC, closed without merging