lad-book:add lad c group output and update submit.md
tinyclub/lad-book pull request #9
Opened 2017-12-07 11:13 UTC by bjwrkj

1.update plan.md, add sponsored link.
2.update submit.md , add exception.md.
3.lad-c output,add exception descritption.
4.update SUMMARY.md,update SUMMARY.md

2017-12-07 12:40 UTC, DeviosLang requested changes

2017-12-07 12:40 UTC, DeviosLang commented on zh-cn/kernel/exception.md
> +从理论角度我们可以笼统的说中断是指的中央处理器(CPU)对系统发生某个事情后作出的一种反应，异常的定义没有明确的规定， 不通的体系架构的定义有一些差异，大体上基本认为异常是由于软件造成的。
不同的体系架构，字打错了

2017-12-07 12:40 UTC, DeviosLang commented on zh-cn/kernel/exception.md
> +|7|Coprocessor Not Available|设备不存在， 指协处理器。在两种情况下会产生该中断：a. CPU 遇到一个转意指令并且EM置位。(b)MP 和 TS 都在置位状态， CPU 遇到wait或一个转意指令。在这种情况下，处理程序在必要应该更新协处理器的状态|
“处理程序在必要应该更新协处理器的状态”这句话有点儿不理解

2017-12-07 12:40 UTC, DeviosLang commented on zh-cn/kernel/exception.md
> +有了访问地址，异常向量偏移，那么我们就可以设计代码框架了。我想当时Linus 应该是这么想的: 一直在研究Unix 操作系统设计，我想我也应该信号到我的操作系统中， 我可以把每个异常对应一个信号，用来做全局通知链，这样一些无需CPU reset解决的，可以做一下告警，告知开发应用程序或者驱动的程序员该如何规范使用当前芯片。 好吧，我要开干了！！！
“我想我也应该信号到我的操作系统中” 这句话不太明白

2017-12-07 12:40 UTC, DeviosLang commented on zh-cn/kernel/exception.md
> +代码写完了，按照软件开发流程，下面就需要测试了， 让我们编写测试例触发上述异常(有的无法触发需要硬件配置)，来验证效果吧。
看样子，上面有的（括号是汉语的格式有的是英语格式本行是英文格式

2017-12-10 17:01 UTC, lzufalcon commented
@bjwrkj close for new PR.

2017-12-10 17:01 UTC, closed without merging